### ISSUE TITLE
Wishlist: Add taskbar/system tray icon app indicator like yad --notification feature

### ISSUE THREAD

**Issue by ghost** [darealshinji/fltk-dialog#1]
It would be great to have this implemented. 

I imagine it would be like this

```sh
fltk-dialog --indicator --command=./my_program_to_run_if_indicator_being_clicked
```

**Comment by darealshinji** [comment]
First, thanks for your interest in my program. A tray icon functionality sounds good, but it's not easy to implement, as FLTK doesn't provide such a feature by itself. But I'll see what I can do.

**Comment by darealshinji** [comment]
Good news: I figured how to create an indicator icon. I have to dlopen() `libappindicator.so.1` and `libgtk-x11-2.0.so.0` so these are not hard dependencies. I still need to do more testing and put it into fltk-dialog. I guess I will also add some sort of "minimize to tray" function.

**Comment by ghost** [comment]
@darealshinji Wow! That is a very good news, indeed.

**Comment by darealshinji** [comment]
I have added this feature. Usage is `fltk-dialog --indicator=COMMAND --indicator-icon=PATH`

Example: `./fltk-dialog --indicator="./fltk-dialog --question" --indicator-icon=/usr/share/icons/hicolor/scalable/apps/deluge.svg && echo yes || echo no`

Should I make the "Launch" entry text in the indicator menu customizable?

PS: resizing the icon and making it usable to libappindicator was appearently the most troublesome part.

**Comment by ghost** [comment]
@darealshinji 
X11 has this very feature you are looking for.  I have a repo (I just uploaded it to git from bzr) you can check out which requires no GTK dependencies
https://github.com/Israel-D/fltk-indicator
It provides both alsa volume control and battery indicator

The most relevant is this:
[make_indicator(Fl_Window* client) ](https://github.com/Israel-D/fltk-indicator/blob/master/src/fltk-indicator.cxx#L1764)
```
Window dock = get_dock();
  if(!dock)
  return;
  int SYSTEM_TRAY_REQUEST_DOCK=0;
  XColor c;
  XImage *image;
  XEvent ev;
  memset(&ev, 0, sizeof(ev));
  ev.xclient.type = ClientMessage;
  ev.xclient.window = dock;
  ev.xclient.message_type = XInternAtom (fl_display, "_NET_SYSTEM_TRAY_OPCODE", False);
  ev.xclient.format = 32;
  ev.xclient.data.l[0] = fl_event_time;
  ev.xclient.data.l[1] = SYSTEM_TRAY_REQUEST_DOCK;
  ev.xclient.data.l[2] = fl_xid(client); // window to be docked
  ev.xclient.data.l[3] = 0;
  ev.xclient.data.l[4] = 0;
  XSendEvent(fl_display, dock, False, NoEventMask, &ev);
  XSync(fl_display, False);
  trap_errors();
  
  
  int x = client->x()+1;
  int y = client->y()+1;
// this gets the color of the pixel BEHIND our docked icon we are adding
  image = XGetImage (fl_display,RootWindow (fl_display, DefaultScreen (fl_display)),
  x, y, 1, 1, AllPlanes, XYPixmap);
  c.pixel = XGetPixel (image, 0, 0);
  XFree (image);
  XQueryColor (fl_display,DefaultColormap(fl_display, DefaultScreen (fl_display)), &c);
  unsigned int BGColor=get_fl_color(&c); //my function to convert rgb X color to FLTK color

  client->color(BGColor); //Make it the same background color as the dock
  client->redraw();
  if (untrap_errors())
  {
  /* Handle failure */
}
```

**Comment by darealshinji** [comment]
Thanks @Israel-D 
I will later take a look at this. Does it work under all or most known DEs?

**Comment by darealshinji** [comment]
This is what I came up with: [gist](https://gist.github.com/darealshinji/18de159f04220a2a2cfc72967534b2c4) | [github branch](https://github.com/darealshinji/fltk-dialog/tree/indicator)

Adding an indicator icon to the tray and running a callback when clicking on it works. But I cannot get a popup menu to work correctly.

**Comment by ghost** [comment]
@darealshinji that's basically the same as what I did.
To solve the popup menu issue (I had it also) was that I pop up a borderless window with Fl_Buttons.  I suppose you  could also add a timer callback to run something like
```
if (popup_window->visible())
  popup_window->hide() ;
```
so it auto hides, I basically have a toggle function that shows or hides the pop up.  Of course I also make the window and hide it right off... then just toggle it when clicked.
This allows me to have a slider window for the volume as well as a right click "menu"
I had an earlier version that worked fine, but could only have the right click menu.  I did it by making a menu above the Fl_Box containing my "status icon".  But I could not effectively call separate things for Right and Left clicks, so I used a button containing the "status icon" and popup borderless windows.

Anyhow, I am going to try out your program, and probably make a Debian package and put it in a PPA later.... if you want I'll give you the debian folder when I get it working

**Comment by darealshinji** [comment]
@Israel-D How do you get the correct size of the tray area, which is needed for the icon size? `win->h()` only returns me the correct size (after the window was resized to fit into the tray) if I put it inside the callback function which removes the tray icon when I clicked it.

edit:

Nevermind, I achieved this using timeouts.

**Comment by darealshinji** [comment]
Adding one icon to the tray is working fine but when I add several this happens:
![screen](https://user-images.githubusercontent.com/5700937/44399482-0c74a700-a548-11e8-8232-810e3938a3f5.png)

**Comment by ghost** [comment]
@darealshinji Weird. That didn't happen to me. (on joe's window manager)

![pp](https://user-images.githubusercontent.com/24475030/44457580-2a203a00-a636-11e8-9809-758922c3bb94.png)

**Comment by darealshinji** [comment]
Maybe it's a bug in MATE.

**Comment by ghost** [comment]
@darealshinji I just had a thought about this.  perhaps the bug is related to xclass....
so maybe do something like (for FLTK code)
```c++
indicator_window->xlcass(name_of_script);
```

**Comment by darealshinji** [comment]
What name am I supposed to set with xclass()? Setting it to "fltk-dialog" or making it different for each instance by appending the pid doesn't fix it.

**Comment by darealshinji** [comment]
I just checked it on different DEs using Ubuntu Live DVDs and it's not working correctly anywhere. On Unity the indicator isn't created at all, it throws an error message and that's it. On XFCE the program closes immediately without any message. And on KDE the indicator is created but the icon isn't visible anywhere.
I guess I have to return to the libappindicator method and keep the current one only as a backup.

**Comment by darealshinji** [comment]
Okay, it's working now in most DEs, except for KDE. The program dlopen()s libappindicator which is supported basically everywhere, except KDE. I _might_ add support for KDE later.

Usage is `--indicator=COMMAND`, i.e. `fltk-dialog --indicator="echo \"Hello World\""`. It'll try to open libappindicator3 first, then libappindicator and then falls back to the legacy X11 method. To only use the legacy method you can use `--force-legacy`, while `--skip-legacy` does the opposite and skips the X11 fallback method.

**Comment by simoniz0r** [comment]
Could you add more functionality to this?  Perhaps the ability to listen for input as yad's tray icon does?

Having a tray app that just exits when you run the payload is not at all useful, IMO...

**Comment by darealshinji** [comment]
@simoniz0r Can you give more information on what it should actually do? Some command line examples maybe what yad does, so I can try to implement it here.

**Comment by ghost** [comment]
@darealshinji 
you use yad like this:
```bash
yad --notification --image="image1" --listen <&3 &
sleep 10
echo "icon:image2">&3
```
This starts the indicator with image1 and after 10 seconds the icon is changed to image2
basically it listens for configuration changes.  so all configurable options (more or less) can be changed by

```bash
echo "configurable_option_name:value" >&3
```
some ideas for configurable options:
menus, icons, dialog, etc...
To use script functions you export it to the shell, and these can be used in the menus, etc...
```bash
function1(){
  run_function2
}
export -f function1
```
Also... it might be good to simply extend classes rather than patch FLTK, that way people could package it for their distributions much easier.  But, that said your program is really cool!

**Comment by darealshinji** [comment]
I'm getting an error when I try to run your yad command:
```
$ ./src/yad --notification --image="image1" --listen <&3 
bash: 3: Bad file descriptor
```

As for the patch: I already reduced the patches an used subclasses instead. I can see if I can use more subclasses.

**Comment by simoniz0r** [comment]
You have to create the pipe first.

```
# create a FIFO file, used to manage the I/O redirection from shell
PIPE=$(mktemp -u --tmpdir ${0##*/}.XXXXXXXX)
mkfifo $PIPE

# attach a file descriptor to the file
exec 3<> $PIPE

# add handler to manage process shutdown
function on_exit() {
    echo "quit" >&3
    rm -f $PIPE
}
trap on_exit EXIT
```

It's all listed in the documentation:
https://sourceforge.net/p/yad-dialog/wiki/NotificationIcon/

**Comment by simoniz0r** [comment]
Also, here's a simple script I've made recently that makes use of this:
https://filebin.net/simonizor/yad-weather

**Comment by darealshinji** [comment]
I have implemented a `--listen` command.

**Comment by darealshinji** [comment]
The indicator will now only be removed if `--auto-close` was given.

By the way, what if I let the program create the FIFO?
``` sh
fifo=$(mktemp -u)
fltk-dialog --indicator="echo Hello" --listen=$fifo &
echo "icon:MyIcon" > $fifo
```

**Comment by simoniz0r** [comment]
Thank you for these additions.  I will give them a try as soon as I have some extra free time.

>By the way, what if I let the program create the FIFO?

I'm not sure what the best practice would be there.  If you were to do that, I would think you would want to provide a unique environment variable that could be used for getting the location of the fifo pipe file.  Most fifo pipes I've seen are created in `/tmp` and use the name of the program being ran along with some randomized numbers as the file name, so the user would need a way to know where the fifo pipe file is in order to use it.

**Comment by darealshinji** [comment]
Here's an idea: if a path was given to the `--listen` command, it will check if it exists and is a FIFO, otherwise create FIFO under that path, or simply listen to STDIN if the path exists and is not a FIFO or if no path was given.

`--listen` >> program listens to STDIN
`--listen=/usr/bin` >> path exists, listen to STDIN
`--listen=/usr/share/tmp-12345` >> cannot create file, listen to STDIN
`--listen=/tmp/tmp-12345` >> create file and listen to it
`--listen=/tmp/tmp-12345` >> file exists and is a FIFO, listen to it

**Comment by darealshinji** [comment]
With all the extra checks things got a bit complicated, plus I ran into some other issues. I'll leave it the way it is. If you want another option to be added or run into a problem, open a new issue report, okay?
