### ISSUE TITLE
No longer runs on CentOS 7

### ISSUE THREAD

**Issue by simoniz0r** [darealshinji/fltk-dialog#3]
As seen here, a user is no longer able to use an AppImage I build because fltk-dialog fails to run on CentOS 7.

```
fltk-dialog: /lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found (required by fltk-dialog) fltk-dialog: /lib64/libstdc++.so.6: version CXXABI_1.3.8' not found (required by fltk-dialog)
fltk-dialog: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fltk-dialog)
```

https://github.com/simoniz0r/Discord-Canary-AppImage/issues/3

**Comment by darealshinji** [comment]
I've set the build system to Ubuntu 14.04. Does it now work?

**Comment by simoniz0r** [comment]
That seems to have fixed the problem.  Thanks!
